http:
  listenAddr: ":8080"

release:
  releaseVersion: "@RELEASE_VERSION@"
  releaseTime: "@RELEASE_TIME@"


database:
  url: root:root@tcp(db:3306)/?charset=utf8&parseTime=true
  maxIdle: 50
  maxActive: 100
  logMode: true
